[colors.primary]
background = '#151218'
foreground = '#e7e0e8'

[colors.selection]
text = '#e7e0e8'
background = '#523c73'

[colors.cursor]
text = '#151218'
cursor = '#d5bbfc'

[colors.normal]
black   = '#151218'
red     = '#e05341'
green   = '#6ed676'
yellow  = '#dbda7b'
blue    = '#9a6add'
magenta = '#a595bd'
cyan    = '#d5bbfc'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06b5f'
green   = '#86e08c'
yellow  = '#e8e797'
blue    = '#e4c8ff'
magenta = '#8369c9'
cyan    = '#8f69b2'
white   = '#ffffff'
