[colors.primary]
background = '#fdf7ff'
foreground = '#1d1b20'

[colors.selection]
text = '#1d1b20'
background = '#e9ddff'

[colors.cursor]
text = '#fdf7ff'
cursor = '#65558f'

[colors.normal]
black   = '#141218'
red     = '#8c150b'
green   = '#09720f'
yellow  = '#7f7d11'
blue    = '#8853ff'
magenta = '#3b2479'
cyan    = '#65558f'
white   = '#1a1a1a'

[colors.bright]
black   = '#2e2e2e'
red     = '#a52b20'
green   = '#138c1a'
yellow  = '#999621'
blue    = '#745fab'
magenta = '#513fff'
cyan    = '#d659ff'
white   = '#1a1a1a'
