[colors.primary]
background = '#1a1110'
foreground = '#f1dedc'

[colors.selection]
text = '#f1dedc'
background = '#73342b'

[colors.cursor]
text = '#1a1110'
cursor = '#ffb4a9'

[colors.normal]
black   = '#1a1110'
red     = '#e04783'
green   = '#9bd66e'
yellow  = '#dba97b'
blue    = '#ca6556'
magenta = '#bf928b'
cyan    = '#ffb4a9'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f95'
green   = '#ade086'
yellow  = '#e8be97'
blue    = '#ffc0b5'
magenta = '#bc5c5f'
cyan    = '#a26b58'
white   = '#ffffff'
