[colors.primary]
background = '#1a110f'
foreground = '#f2dedb'

[colors.selection]
text = '#f2dedb'
background = '#943726'

[colors.cursor]
text = '#1a110f'
cursor = '#ffb4a5'

[colors.normal]
black   = '#1a110f'
red     = '#e14984'
green   = '#9bd66e'
yellow  = '#dbaa7b'
blue    = '#c56652'
magenta = '#bf9289'
cyan    = '#ffb4a5'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f94'
green   = '#ade086'
yellow  = '#e8bf97'
blue    = '#ffc1b0'
magenta = '#bd5c5b'
cyan    = '#a06c56'
white   = '#ffffff'
