[colors.primary]
background = '#1a1111'
foreground = '#f0dede'

[colors.selection]
text = '#f0dede'
background = '#733336'

[colors.cursor]
text = '#1a1111'
cursor = '#ffb3b3'

[colors.normal]
black   = '#1a1111'
red     = '#e14986'
green   = '#9dd66e'
yellow  = '#dba87b'
blue    = '#d05d5b'
magenta = '#bf9191'
cyan    = '#ffb3b3'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f97'
green   = '#aee086'
yellow  = '#e8bd97'
blue    = '#ffbfbf'
magenta = '#bb5b6a'
cyan    = '#a9685e'
white   = '#ffffff'
